from enum import Enum


class error_code(Enum):
    NO_SUCH_FILE_ERROR = 1
    NO_SUCH_COURSE_ERROR = 2
    COURSE_EXISTED_ERROR = 3
    NO_SUCH_COMMAND_ERROR = 4
    PARAMETER_ERROR = 5
    NO_INPUT_ERROR = 6
    PARAMETER_FORMAT_ERROR = 7
    UNIMPLEMENT_ERROR = 8